/*function sort(zone1,zone2) {
    const overlappingBooks = zone1.filter(book => zone2.includes(book));

    console.log(overlappingBooks);
}







const genre =[

    Romance =["The Love Hypothesis",
        "The Spanish Love Deception",
        "Flirting Lessons",
        "The Exiled Prince",
        "Mine for Tonight",
        "Crown of Wrath",
        "Stardust Child",
        "Bound By Fire and Scales",
        "Winter's Fate",
        "Love at First Flight",
        "Home is Where the Sunflower Grows",
        "Hear My Heart",
        "Storm and Sea",
        "Only Hope",
        "Fable for the End of the World",
        "The Duke and I",
        "The Viscount Who Loved Me",
        "An Offer from a Gentleman",
        "Romancing Mr. Bridgerton",
        "To Sir Philip, With Love",
        "When He Was Wicked",
        "It's In His Kiss",
        "Red, White & Royal Blue",
        "The Song of Achilles",
        "The Love Lyric",
        "Scythe",
        "Divergent",
        "Insurgent",
        "Allegiant",
        "Matched",
        "Shatter Me",
        "The Selection",
        "Delirium",
        "Red Queen",
        "Legend",
        "The 5th Wave",
        "Unravel Me",
        "The Darkest Minds",
        "Angelfall",
        "Ignite Me",
        "Interview with the Vampire",
        "The Vampire Lestat",
        "One Dark Window",
        "Gray After Dark",
        "Frankenstein",
        "The Fault in Our Stars",
        "Thirteen Reasons Why",
        "Wicked",
        "Vampire Academy",
        "Beautiful Creatures",
        "Ella Enchanted",
        "Switched",
        "Graceling",
        "Pretty Little Liars",
        "The Vincent Brothers",
        "Poison Study",
        "The Darkest Pleasure",
        "Born at Midnight","Powerless",
        "Once Upon a Broken Heart",
        "The Ballad of Never After",
        "A Curse for True Love",
        "Legendborn",
        "Yumi and the Nightmare Painter",
        "The Sun and the Star",
        "The King of Battle and Blood",
        "Curse of Shadows and Thorns",
        "City of Bones",
        "One Dark Window"],

    Dystopian = ["Unwind",
        "Thunderhead",
        "Scythe",
        "Divergent",
        "Insurgent",
        "Allegiant",
        "The Maze Runner",
        "Matched",
        "Shatter Me",
        "The Selection",
        "Delirium",
        "Red Queen",
        "Red Rising",
        "Legend",
        "The 5th Wave",
        "Unravel Me",
        "The Darkest Minds",
        "The Handmaid’s Tale",
        "Angelfall",
        "Ignite Me",
        "Fable for the End of the World",
        "The Stand",
        "World War Z",
        "Bird Box",
        "Poison Study",
    ],



    Horror = [ "When the Bones Sing",
        "It",
        "The Shining",
        "Mexican Gothic",
        "Misery",
        "Salem's Lot",
        "The Stand",
        "World War Z",
        "Bird Box",
        "Coraline",
        "The Exorcist",
        "Cujo",
        "Interview with the Vampire",
        "The Vampire Lestat",
        "Home is Where the Bodies Are",
        "That's Not My Name",
        "One Dark Window",
        "Gray After Dark",
        "The Silence of the Lambs",
        "Frankenstein",
        "Fable for the End of the World",
        "The 5th Wave",
        "The Handmaid’s Tale",
        "Angelfall",
    ],

    YoungAdult =["The Fault in Our Stars",
        "Harry Potter and the Philosopher's Stone",
        "Harry Potter and the Chamber of Secrets",
        "Harry Potter and the Goblet of Fire",
        "Harry Potter and the Deathly Hallows",
        "Harry Potter and the Order of the Phoenix",
        "Harry Potter and the Half-Blood Prince",
        "Harry Potter and the Prisoner of Azkaban",
        "Thirteen Reasons Why",
        "Wicked",
        "Vampire Academy",
        "Beautiful Creatures",
        "Ella Enchanted",
        "Switched",
        "Graceling",
        "Pretty Little Liars",
        "The Vincent Brothers",
        "Poison Study",
        "The Darkest Pleasure",
        "Born at Midnight",
        "Vampire Academy",
        "Pretty Little Liars",
        "Poison Study",
        "The Darkest Pleasure",
        "The Familiar",
        "The King of Battle and Blood",
        "City of Bones",
        "One Dark Window"
    ],

    Fantasy=["Somewhere Beyond the Sea",
        "The Familiar",
        "The Ballad of Songbirds and Snakes",
        "Powerless",
        "The Midnight Library",
        "Once Upon a Broken Heart",
        "The Ballad of Never After",
        "A Curse for True Love",
        "The Chalice of the Gods",
        "Legendborn",
        "The Atlas Six",
        "Yumi and the Nightmare Painter",
        "The Sun and the Star",
        "The King of Battle and Blood",
        "Curse of Shadows and Thorns",
        "The Hunger Games",
        "Catching Fire",
        "Mockingjay",
        "The Sunlit Man",
        "I Am Made of Death",
        "The Lightning Thief",
        "The Sea of Monsters",
        "The Titan’s Curse",
        "City of Bones",
        "One Dark Window",
        "The Exiled Prince",
        "Crown of Wrath",
        "Stardust Child",
        "Bound By Fire and Scales",
        "Winter's Fate",
        "The Duke and I",
        "The Viscount Who Loved Me",
        "Romancing Mr. Bridgerton",
        "Red, White & Royal Blue",
        "The Song of Achilles",
        "Shatter Me",
        "The Selection",
        "Red Queen",
        "Red Rising",
        "The Darkest Minds",
        "Angelfall",
        "Ignite Me",
        "Interview with the Vampire",
        "The Vampire Lestat",
        "The Fault in Our Stars",
        "Harry Potter and the Philosopher's Stone",
        "Harry Potter and the Chamber of Secrets",
        "Harry Potter and the Goblet of Fire",
        "Harry Potter and the Deathly Hallows",
        "Harry Potter and the Order of the Phoenix",
        "Harry Potter and the Half-Blood Prince",
        "Harry Potter and the Prisoner of Azkaban",
        "Thirteen Reasons Why",
        "Wicked",
        "Vampire Academy",
        "Beautiful Creatures",
        "Ella Enchanted",
        "Switched",
        "Graceling",
        "Pretty Little Liars",
        "The Vincent Brothers",
        "Poison Study",
        "The Darkest Pleasure",
        "Born at Midnight"
    ]

]